name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test Spring Boot App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          cache-dependency-path: '**/pom.xml'
      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build application and run test
        run: ./mvnw clean package

      - name: upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-test-reports
          path: target/surefire-reports/